In [1]:
import torch

# Creating a tensor
tensor_example = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Displaying basic properties of tensors
print(f"Shape of tensor: {tensor_example.shape}")
print(f"Data type of tensor: {tensor_example.dtype}")
print(tensor_example)

Shape of tensor: torch.Size([2, 3])
Data type of tensor: torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [2]:
import torch

# Tensor to be modified
tensor_example = torch.tensor([[1, 2, 3], [4, 5, 6],[8,9,0]])

# Displaying basic properties of tensors
print(f"Shape of tensor: {tensor_example.shape}")
print(f"Data type of tensor: {tensor_example.dtype}")
print(tensor_example)

Shape of tensor: torch.Size([3, 3])
Data type of tensor: torch.int64
tensor([[1, 2, 3],
        [4, 5, 6],
        [8, 9, 0]])


In [1]:
import torch

# Creating three tensors
tensor_a = torch.tensor([[1, 2], [3, 4]], dtype=torch.int32) # 2x2 tensor
tensor_b = torch.tensor([[5, 6], [7, 8]], dtype=torch.int32) # 2x2 tensor
tensor_c = torch.tensor([[1], [2]], dtype=torch.int32) # 2x1 tensor

# Addition
tensor_sum = torch.add(tensor_a, tensor_b)
print(f"Tensor Addition:\n{tensor_sum}\n")

# Element-wise Multiplication
tensor_product = torch.mul(tensor_a, tensor_b)
print(f"Element-wise Multiplication:\n{tensor_product}\n")

# Matrix Multiplication 
tensor_matmul = torch.matmul(tensor_a, tensor_c)
print(f"Matrix Multiplication:\n{tensor_matmul}\n")

# Broadcasted Addition (Tensor + scalar)
tensor_add_scalar = tensor_a + 5
print(f"Broadcasted Addition (Adding scalar value):\n{tensor_add_scalar}\n")

# Broadcasted Addition between tensors of different shapes: 
broadcasted_sum = tensor_a + tensor_c
print(f"Broadcasted Addition: \n{broadcasted_sum}\n")

# Broadcasted Multiplication between tensors of different shapes:
broadcasted_mul = tensor_a * tensor_c
print(f"Broadcasted Multiplication: \n{broadcasted_mul}\n")

Tensor Addition:
tensor([[ 6,  8],
        [10, 12]], dtype=torch.int32)

Element-wise Multiplication:
tensor([[ 5, 12],
        [21, 32]], dtype=torch.int32)

Matrix Multiplication:
tensor([[ 5],
        [11]], dtype=torch.int32)

Broadcasted Addition (Adding scalar value):
tensor([[6, 7],
        [8, 9]], dtype=torch.int32)

Broadcasted Addition: 
tensor([[2, 3],
        [5, 6]], dtype=torch.int32)

Broadcasted Multiplication: 
tensor([[1, 2],
        [6, 8]], dtype=torch.int32)



In [1]:
import torch

# Creating three tensors
heroes = torch.tensor([[2, 3], [4, 5]], dtype=torch.int32) # 2x2 tensor
villains = torch.tensor([[7, 8], [9, 10]], dtype=torch.int32) # 2x2 tensor
sidekicks = torch.tensor([[2], [3]], dtype=torch.int32) # 2x1 tensor

# Addition
combined_power = torch.add(heroes, villains)
print(f"Combined Power:\n{combined_power}\n")

# Element-wise Multiplication
power_product = torch.mul(heroes, villains)
print(f"Power Product:\n{power_product}\n")

# Matrix Multiplication 
team_effectiveness = torch.matmul(heroes, sidekicks)
print(f"Team Effectiveness:\n{team_effectiveness}\n")

# TODO: Add code for broadcasted addition (tensor + scalar)
tensor_add_scalar = heroes + 5
print(f"Broadcasted Addition (Adding scalar value):\n{tensor_add_scalar}\n")
# TODO: Add code for broadcasted addition between tensors of different shapes (heroes + sidekicks)
broadcasted_sum = villains + sidekicks
print(f"Broadcasted Addition: \n{broadcasted_sum}\n")
# TODO: Add code for broadcasted multiplication between tensors of different shapes (heroes * sidekicks)
broadcasted_mul = heroes * sidekicks
print(f"Broadcasted Multiplication: \n{broadcasted_mul}\n")

Combined Power:
tensor([[ 9, 11],
        [13, 15]], dtype=torch.int32)

Power Product:
tensor([[14, 24],
        [36, 50]], dtype=torch.int32)

Team Effectiveness:
tensor([[13],
        [23]], dtype=torch.int32)

Broadcasted Addition (Adding scalar value):
tensor([[ 7,  8],
        [ 9, 10]], dtype=torch.int32)

Broadcasted Addition: 
tensor([[ 9, 10],
        [12, 13]], dtype=torch.int32)

Broadcasted Multiplication: 
tensor([[ 4,  6],
        [12, 15]], dtype=torch.int32)



In [2]:
import torch

# Creating a tensor for manipulation
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshape the tensor
reshaped_tensor = tensor_a.view(3, 2)

# Flatten the tensor
flattened_tensor = tensor_a.view(-1)

print(f"Original Tensor:\n{tensor_a}\n")
print(f"Reshaped Tensor:\n{reshaped_tensor}\n")
print(f"Flattened Tensor:\n{flattened_tensor}")

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Reshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Flattened Tensor:
tensor([1, 2, 3, 4, 5, 6])


In [3]:
import torch

# Creating a tensor for manipulation
tensor_example = torch.tensor([[1, 2, 3, 4], 
                               [5, 6, 7, 8], 
                               [9, 10, 11, 12], 
                               [13, 14, 15, 16]])

# TODO: Reshape the tensor into an 8x2 tensor
reshaped_tensor = tensor_example.view(8, 2)

# Displaying the original and reshaped tensors
print(f"Original Tensor: \n{tensor_example}\n")
print(f"Reshaped Tensor: \n{reshaped_tensor}")

Original Tensor: 
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

Reshaped Tensor: 
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]])


In [4]:
import torch

# Creating a tensor for manipulation
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshape the tensor
reshaped_tensor = tensor_a.view(3, 2)

# TODO: Flatten the tensor
flattened_tensor = tensor_a.view(-1)

print(f"Original Tensor:\n{tensor_a}\n")
print(f"Reshaped Tensor:\n{reshaped_tensor}\n")
print(f"Flattened Tensor:\n{flattened_tensor}")

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Reshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Flattened Tensor:
tensor([1, 2, 3, 4, 5, 6])


In [5]:
import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset

# Define a simple array as input data
X = np.array([[1.0, 2.0], [2.0, 1.0], [3.0, 4.0], [4.0, 3.0]])
# Define the target outputs for our dataset
y = np.array([0, 1, 0, 1])

# Convert X and y into PyTorch tensors
X_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.int32)

# Create a tensor dataset and data loader
dataset = TensorDataset(X_tensor, y_tensor)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

# Iterate through the dataloader
for batch_X, batch_y in dataloader:
    print(f"Batch X:\n{batch_X}")
    print(f"Batch y:\n{batch_y}\n")

Batch X:
tensor([[4., 3.],
        [2., 1.]])
Batch y:
tensor([1, 1], dtype=torch.int32)

Batch X:
tensor([[3., 4.],
        [1., 2.]])
Batch y:
tensor([0, 0], dtype=torch.int32)



In [6]:
import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset

# Define a simple array as input data for superhero powers
Powers = np.array([[5.0, 3.0], [2.0, 4.0], [1.0, 2.0], [3.0, 6.0]])
# Define the target outputs representing hero or villain
labels = np.array([0, 1, 0, 1])

# Convert Powers and labels into PyTorch tensors
Powers_tensor = torch.tensor(Powers, dtype=torch.float32)
labels_tensor = torch.tensor(labels, dtype=torch.int32)

# Create a tensor dataset and data loader
dataset = TensorDataset(Powers_tensor, labels_tensor)
dataloader = DataLoader(dataset, batch_size=3, shuffle=True)  # TODO: Change batch size to 3

# Iterate through the dataloader
for batch_Powers, batch_labels in dataloader:
    print(f"Batch Powers:\n{batch_Powers}")
    print(f"Batch Labels:\n{batch_labels}\n")

Batch Powers:
tensor([[3., 6.],
        [5., 3.],
        [2., 4.]])
Batch Labels:
tensor([1, 0, 1], dtype=torch.int32)

Batch Powers:
tensor([[1., 2.]])
Batch Labels:
tensor([0], dtype=torch.int32)



In [7]:
import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset

# Define a simple array as input data for superhero powers
Powers = np.array([[5.0, 3.0], [2.0, 4.0], [1.0, 2.0], [3.0, 6.0]])
# Define the target outputs representing hero or villain
labels = np.array([0, 1, 0, 1])

# Convert Powers and labels into PyTorch tensors
Powers_tensor = torch.tensor(Powers, dtype=torch.float32)
labels_tensor = torch.tensor(labels, dtype=torch.int32)

# Create a tensor dataset and data loader
dataset = TensorDataset(Powers_tensor, labels_tensor)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

# Iterate through the dataloader
for batch_Powers, batch_labels in dataloader:
    print(f"Batch Powers:\n{batch_Powers}")
    print(f"Batch Labels:\n{batch_labels}\n")

Batch Powers:
tensor([[3., 6.],
        [5., 3.]])
Batch Labels:
tensor([1, 0], dtype=torch.int32)

Batch Powers:
tensor([[2., 4.],
        [1., 2.]])
Batch Labels:
tensor([1, 0], dtype=torch.int32)



In [1]:
import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset

# Define a simple array as input data
X = np.array([[1.0, 2.0], [2.0, 1.0], [3.0, 4.0], [4.0, 3.0]])
# Define the target outputs for our dataset
y = np.array([0, 1, 0, 1])

# Convert X and y into PyTorch tensors
X_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.int32)

# TODO: Create a tensor dataset from the tensors X_tensor and y_tensor
dataset = TensorDataset(X_tensor,y_tensor)

# TODO: Create a data loader from the dataset with batch_size 2 and shuffle enabled
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

# Iterate through the dataloader
for batch_X, batch_y in dataloader:
    print(f"Batch X:\n{batch_X}")
    print(f"Batch y:\n{batch_y}\n")

Batch X:
tensor([[3., 4.],
        [2., 1.]])
Batch y:
tensor([0, 1], dtype=torch.int32)

Batch X:
tensor([[1., 2.],
        [4., 3.]])
Batch y:
tensor([0, 1], dtype=torch.int32)



In [2]:
import torch
import torch.nn as nn

# Defining an input tensor
input_tensor = torch.tensor([[5.0, 6.0]], dtype=torch.float32)

# Creating a linear layer with 2 input features and 3 output features
layer = nn.Linear(in_features=2, out_features=3)

# Defining a ReLU activation function
relu = nn.ReLU()

# Defining a Sigmoid activation function
sigmoid = nn.Sigmoid()

# Processing the input through the linear layer 
output_tensor = layer(input_tensor)

# Applying the ReLU function to the output of the linear layer
activated_output_relu = relu(output_tensor)

# Applying the Sigmoid function to the output of the linear layer
activated_output_sigmoid = sigmoid(output_tensor)

# Displaying the original input tensor
print(f"Input Tensor:\n{input_tensor}\n")

# Displaying the output before activation to see the linear transformation effect
print(f"Output Tensor Before Activation:\n{output_tensor}\n")

# Displaying the output after activation to observe the effect of ReLU
print(f"Output Tensor After ReLU Activation:\n{activated_output_relu}\n")

# Displaying the output after activation to observe the effect of Sigmoid
print(f"Output Tensor After Sigmoid Activation:\n{activated_output_sigmoid}")

Input Tensor:
tensor([[5., 6.]])

Output Tensor Before Activation:
tensor([[ 0.2411, -4.1630,  0.2912]], grad_fn=<AddmmBackward0>)

Output Tensor After ReLU Activation:
tensor([[0.2411, 0.0000, 0.2912]], grad_fn=<ReluBackward0>)

Output Tensor After Sigmoid Activation:
tensor([[0.5600, 0.0153, 0.5723]], grad_fn=<SigmoidBackward0>)


In [4]:
import torch
import torch.nn as nn

# TODO: Define an input tensor with one more value
input_tensor = torch.tensor([[1.0, 2.0,3.0]], dtype=torch.float32)

# TODO: Change the linear layer to have 3 input features and 2 output features
layer = nn.Linear(in_features=3, out_features=2)

# Define a ReLU activation function 
relu = nn.ReLU()

# Define a Sigmoid activation function
sigmoid = nn.Sigmoid()

# Process the input through the linear layer to get initial output
output_tensor = layer(input_tensor)

# Apply the ReLU function to the output of the linear layer
activated_output_relu = relu(output_tensor)

# Apply the Sigmoid function to the output of the linear layer
activated_output_sigmoid = sigmoid(output_tensor)

# Display the original input tensor
print(f"Input Tensor:\n{input_tensor}\n")

# Display the output before activation to see the linear transformation effect
print(f"Output Tensor Before Activation:\n{output_tensor}\n")

# Display the output after activation to observe the effect of ReLU
print(f"Output Tensor After ReLU Activation:\n{activated_output_relu}\n")

# Display the output after activation to observe the effect of Sigmoid
print(f"Output Tensor After Sigmoid Activation:\n{activated_output_sigmoid}")

Input Tensor:
tensor([[1., 2., 3.]])

Output Tensor Before Activation:
tensor([[ 1.0678, -1.3507]], grad_fn=<AddmmBackward0>)

Output Tensor After ReLU Activation:
tensor([[1.0678, 0.0000]], grad_fn=<ReluBackward0>)

Output Tensor After Sigmoid Activation:
tensor([[0.7442, 0.2058]], grad_fn=<SigmoidBackward0>)


In [6]:
import torch
import torch.nn as nn

input_tensor = torch.tensor([[1.0, 2.0]], dtype=torch.float32)

# Create linear layer with specified number of input and output features
layer = nn.Linear(in_features=2, out_features=3)

# Process the input tensor through the linear layer to get initial output
output_tensor = layer(input_tensor)

# TODO: Define a ReLU activation function
relu = nn.ReLU()
# TODO: Apply the ReLU function to the output tensor
activated_output_relu = relu(output_tensor)
# Define a Sigmoid activation function
sigmoid = nn.Sigmoid()

# Apply the Sigmoid function to the output tensor
activated_output_sigmoid = sigmoid(output_tensor)

print(f"Input Tensor:\n{input_tensor}\n")
print(f"Output Tensor Before Activation:\n{output_tensor}\n")
print(f"Output Tensor After ReLU Activation:\n{activated_output_relu}\n")
print(f"Output Tensor After Sigmoid Activation:\n{activated_output_sigmoid}")

Input Tensor:
tensor([[1., 2.]])

Output Tensor Before Activation:
tensor([[ 0.1368,  0.6893, -1.6813]], grad_fn=<AddmmBackward0>)

Output Tensor After ReLU Activation:
tensor([[0.1368, 0.6893, 0.0000]], grad_fn=<ReluBackward0>)

Output Tensor After Sigmoid Activation:
tensor([[0.5342, 0.6658, 0.1569]], grad_fn=<SigmoidBackward0>)


In [9]:
import torch
import torch.nn as nn

# Define an input tensor with specific values
input_tensor = torch.tensor([[7.5, 3.0, 9.9]], dtype=torch.float32) 

# TODO: Create a linear layer with 3 input features and 4 output features
layer = nn.Linear(in_features=3,out_features=4)
# TODO: Define a ReLU activation function 
relu = nn.ReLU()
# TODO: Define a Sigmoid activation function
sigmoid = nn.Sigmoid()
# TODO: Process the input through the linear layer to get initial output
output_tensor = layer(input_tensor)
# TODO: Apply the ReLU function to the output of the linear layer
activated_output_relu = relu(output_tensor)
# TODO: Apply the Sigmoid function to the output of the linear layer
activated_output_sigmoid = sigmoid(output_tensor)
# TODO: Display the original input tensor
print(input_tensor)
# TODO: Display the output before activation to see the linear transformation effect
print(output_tensor)
# TODO: Display the output after activation to observe the effect of ReLU
print(activated_output_relu)
# TODO: Display the output after activation to observe the effect of Sigmoid
print(activated_output_sigmoid)

tensor([[7.5000, 3.0000, 9.9000]])
tensor([[ 4.2580, -8.2141,  6.2887, -5.1831]], grad_fn=<AddmmBackward0>)
tensor([[4.2580, 0.0000, 6.2887, 0.0000]], grad_fn=<ReluBackward0>)
tensor([[9.8605e-01, 2.7073e-04, 9.9815e-01, 5.5794e-03]],
       grad_fn=<SigmoidBackward0>)
